"""Add first tables

Revision ID: ecd4323b98ab
Revises: 
Create Date: 2025-04-05 15:32:40.057414

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ecd4323b98ab'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('achievements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type_of_achievement', sa.String(length=50), nullable=False),
    sa.Column('date_of_award_of_achievement', sa.Date(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_achievements_id'), 'achievements', ['id'], unique=False)
    op.create_table('foreign_language_certificate',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('language', sa.String(length=50), nullable=False),
    sa.Column('certificate_type', sa.String(length=50), nullable=False),
    sa.Column('level', sa.String(length=10), nullable=False),
    sa.Column('series_and_number', sa.String(length=50), nullable=False),
    sa.Column('date_of_issue', sa.Date(), nullable=False),
    sa.Column('file_path', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scientific_research_works',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scientific_research_form', sa.String(), nullable=False),
    sa.Column('date_of_publication', sa.Date(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('scientific_research_works')
    op.drop_table('foreign_language_certificate')
    op.drop_index(op.f('ix_achievements_id'), table_name='achievements')
    op.drop_table('achievements')
    # ### end Alembic commands ###
